results_dir: "results"
sample_to_fastq:
    "HSV1_Kos_d27_12hpi_DMSO":
        R1: "input/HSV1_Kos_d27_12hpi_DMSO_S1_L002_R1_001.fastq.gz"
        R2: "input/HSV1_Kos_d27_12hpi_DMSO_S1_L002_R2_001.fastq.gz"

#As far as I know, you must compile your own hisat2 in order for the hisat2_path
#to work correctly. You can not module load it. You can not conda activate it.
#This is because the scripts will be looking for executables such as extract_exons.py
#in a specific place
hisat2_path: "/gpfs/scratch/gp1269/GLORI/hisat2"
hisat2_index_dir: "/gpfs/scratch/gp1269/GLORI/HISAT2_index_from_Fox/script_output_attempt_2/"
reference_fasta: "/gpfs/scratch/gp1269/GLORI/HISAT2_index_from_Fox/GRCh38.primary_assembly.genome.nochr.HSV.fa"
reference_gtf: "/gpfs/scratch/gp1269/GLORI/HISAT2_index_from_Fox/gencode.v45.primary_assembly.annotation.nochr.gtf"
db_path: "/gpfs/scratch/gp1269/GLORI/db_files"
